### ISSUE TITLE
pytest 3.0 checklist

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1877]
- [x] Wait for pytest 3.0
- [x] Wait for https://github.com/pytest-dev/pytest-bdd/pull/193
- [x] Wait for (or do) pytest-bdd release
- [x] Update requirements
- [x] Replace `getfuncargvalue` by `getfixturevalue`
- [x] Use `pytest.approx` in `_partial_compare_float` in `tests.utils`
- [x] Set `__tracebackhide__` to callables only ignoring relevant exceptions
- [x] Maybe use `pytest_make_parametrize_id` to improve parametrization IDs?
- [x] Use `pytest` instead of `py.test`
- [x] Replace `yield_fixture` by `fixture`
- [x] Check if we can use `None` for parametrizing IDs somewhere

**Comment by The-Compiler** [comment]
Reverted for now as I ran into a very odd issue with frozen tests on Windows: https://github.com/pytest-dev/pytest/issues/1832

**Comment by The-Compiler** [comment]
I added a workaround in 853f4cd9d83c30ea59680648c06f38c7f159ba6d and updated to pytest 3.0! :tada:
