### ISSUE TITLE
Infrastructure/Travis meta-issue

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#474]
Filters
-------

- [ ] Only build docs if needed
- [ ] Don't lint/test if only docs are changed

Server
------

(obsolete as we moved to Travis)

- [ ] ~~Set up server monitoring for buildbot VMs~~
- [ ] ~~Set up unattended upgrades on buildbot VMs~~
- [ ] ~~Set `$XDG_RUNTIME_DIR` on Archlinux buildbot~~

Maybe switch to Docker instead, and e.g. do a nightly image rebuild?

Releasing
----------

- [ ] Include built manpage in releases
- [ ] Move releasing process to buildbot so we can only push a `vX.Y.Z` tag, wait, download stuff, and release.
  - [ ] windows standalone exe (32/64bit)
  - [ ] windows MSI
  - [ ] sdist
  - [ ] run setup.py (from sdist?) to verify it's running correctly

Testing
-------

- [ ] Also test with distro-specific library versions for python dependencies?

Other
-----

- [x] Get rid of devpi because it doesn't seem to update from PyPI correctly
- [x] ~~Maybe use [pip-accel](https://github.com/paylogic/pip-accel)~~
- [x] Use real `requirements.txt` files for dependencies. Also I should reread [setup.py vs requirements.txt](https://caremad.io/2013/07/setup-vs-requirement/) and [install_requires vs. Requirements files](https://packaging.python.org/en/latest/requirements.html). [requires.io](https://requires.io/) seems like a good thing to use.
- [x] It seems [tox](http://tox.readthedocs.org/en/latest/) can help simplify a lot of stuff we currently do in [init_venv.py](https://github.com/The-Compiler/qutebrowser/blob/master/scripts/init_venv.py) and [run_checks.py](https://github.com/The-Compiler/qutebrowser/blob/master/scripts/run_checks.py).

**Comment by The-Compiler** [comment]
Retargeting this to v0.3 because I want to get v0.2 out ASAP.

**Comment by The-Compiler** [comment]
#772 and #1739 track the remaining bits, the rest is either implemented or superseded.
