### ISSUE TITLE
pytest cleanups/improvements

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#660]
I'm gathering things about the tests I'd like to clean up/refactor here. Any comments/additions would be appreciated if you have any, @hackebrot @nicoddemus!

- [x] Rewrite remaining tests to use pytest instead of `unittest.TestCase`: (PR: #663)
    - `utils/test_log.py`
    - `utils/usertypes/test_enum.py`
    - `utils/usertypes/test_neighborlist.py`
    - `misc/test_lineparser.py`
    - `misc/test_crashdialog.py`
- [x] Get rid of classes for tests where applicable and maybe refactor `setup` fixtures to something more pytest-like.
- [x] Maybe convert things in `stubs.py` to pytest fixtures instead of having a `stubs` fixture?
- [x] Replace `mocker` by `monkeypatch` where applicable (e.g. to use the `config_stub` fixture from #659) as it has a [nicer API](http://pytest.org/latest/monkeypatch.html).
- [x] Maybe split `test_configtypes` into multiple files as it's getting quite big (>2200 lines)
- [x] When using `mocker`, use the `Mock` attribute from its fixture (see https://github.com/pytest-dev/pytest-mock/pull/11) instead of importing `unittest.mock`. (*not doing this, as there's only one place where mock is actually used with mocker*)
- [x] Adjust `test_readline.py` to test with a real `QLineEdit` instead of a mock. (PR: #679)
- [x] Get rid of `log.py` - see https://github.com/hackebrot/qutebrowser/issues/8

**Comment by nicoddemus** [comment]
> Maybe convert things in stubs.py to pytest fixtures instead of having a stubs fixture?

Particularly I'm OK with the current approach, as `stubs` contains pure python subs, and those are accessed using a fixture, but I would love to hear if you have other mechanism in mind. :smile:

> Replace mocker by monkeypatch where applicable (e.g. to use the config_stub fixture from #659) as it has a nicer API.

Just to comment that I have the same philosophy too, use `monkeypatch` where simple patching is required, but fallback to `MagicMock` when more *serious* mocking is needed. :wink: 

It seems like a pretty complete and well thought to-do list to me. :smile:

**Comment by The-Compiler** [comment]
I think it's about time to admit qutebrowser has made the jump to pytest and close this :laughing: 

I looked through the tests and found one off-hand where it could be simplified using parametrization: 2b496a81ef5cbba6fa66c230ef6ae42746adec0a

**Comment by hackebrot** [comment]
😃 👍

**Comment by nicoddemus** [comment]
Hehehe :grin:
